In [1]:

print("=" * 65)
print("        BASIC DATA PREPROCESSING USING PYTHON")
print("                  UCI IRIS DATASET")
print("=" * 65)

print("\nTasks Performed:")
print("1. Dataset Loading")
print("2. Dataset Exploration")
print("3. Missing Value Handling")
print("4. Categorical Data Encoding")
print("5. Numerical Data Normalization")
print("6. Final Preprocessed Dataset")
print("=" * 65)

=================================================================
        BASIC DATA PREPROCESSING USING PYTHON
                  UCI IRIS DATASET
=================================================================

Tasks Performed:
1. Dataset Loading
2. Dataset Exploration
3. Missing Value Handling
4. Categorical Data Encoding
5. Numerical Data Normalization
6. Final Preprocessed Dataset
=================================================================

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, MinMaxScaler

print("✓ Required libraries imported successfully.")

✓ Required libraries imported successfully.

In [3]:
import os

items = os.listdir()

print("Files and folders in the current directory:\n")

for item in items:
    print("📁" if os.path.isdir(item) else "📄", item)

Files and folders in the current directory:

📁 .ipynb_checkpoints
📄 Assignment No. 6.ipynb
📄 Experiment4.ipynb
📄 Experiment5.ipynb
📄 Untitled.ipynb

In [7]:
import os

dataset_folder = r"D:\AIML LAB"

print("Dataset folder:")
print(dataset_folder)

print("\nFiles available:")
print("-" * 50)

for item in os.listdir(dataset_folder):
    print("📁" if os.path.isdir(os.path.join(dataset_folder, item)) else "📄", item)

Dataset folder:
D:\AIML LAB

Files available:
--------------------------------------------------
📁 iris
📄 iris.zip

In [8]:
import os

iris_folder = r"D:\AIML LAB\iris"

print("Iris dataset folder:")
print(iris_folder)

print("\nFiles inside the folder:")
print("-" * 60)

for item in os.listdir(iris_folder):
    full_path = os.path.join(iris_folder, item)
    print("📁" if os.path.isdir(full_path) else "📄", item)

Iris dataset folder:
D:\AIML LAB\iris

Files inside the folder:
------------------------------------------------------------
📄 bezdekIris.data
📄 Index
📄 iris.data
📄 iris.names

In [9]:
import pandas as pd

file_path = r"D:\AIML LAB\iris\iris.data"


columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

df = pd.read_csv(file_path, header=None, names=columns)

print("✓ Dataset loaded successfully!")
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

✓ Dataset loaded successfully!
Rows    : 150
Columns : 5

In [10]:
print("First 10 records")
print("=" * 80)

display(df.head(10))

First 10 records
================================================================================

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [11]:
print("Dataset Information")
print("=" * 80)

df.info()

Dataset Information
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [12]:
print("Statistical Summary")
print("=" * 80)

display(df.describe())

Statistical Summary
================================================================================

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [13]:
print("Missing Values")
print("=" * 80)

missing_values = df.isnull().sum()

display(missing_values.to_frame(name="Missing Count"))

Missing Values
================================================================================

              Missing Count
sepal_length              0
sepal_width               0
petal_length              0
petal_width               0
species                   0

In [14]:

df_preprocessed = df.copy()

df_preprocessed.loc[0, "sepal_length"] = np.nan
df_preprocessed.loc[5, "sepal_width"] = np.nan
df_preprocessed.loc[10, "petal_width"] = np.nan

print("Missing values introduced for demonstration:")
print("=" * 60)

display(df_preprocessed.isnull().sum().to_frame(name="Missing Count"))

Missing values introduced for demonstration:
============================================================

              Missing Count
sepal_length              1
sepal_width               1
petal_length              0
petal_width               1
species                   0

In [15]:

numeric_columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width"
]

for column in numeric_columns:
    df_preprocessed[column] = df_preprocessed[column].fillna(
        df_preprocessed[column].mean()
    )

print("Missing values after mean imputation:")
print("=" * 60)

display(df_preprocessed.isnull().sum().to_frame(name="Missing Count"))

Missing values after mean imputation:
============================================================

              Missing Count
sepal_length              0
sepal_width               0
petal_length              0
petal_width               0
species                   0

In [16]:
print("Dataset after handling missing values")
print("=" * 80)

display(df_preprocessed.head(10))

Dataset after handling missing values
================================================================================

   sepal_length  sepal_width  petal_length  petal_width      species
0      5.848322     3.500000           1.4          0.2  Iris-setosa
1      4.900000     3.000000           1.4          0.2  Iris-setosa
2      4.700000     3.200000           1.3          0.2  Iris-setosa
3      4.600000     3.100000           1.5          0.2  Iris-setosa
4      5.000000     3.600000           1.4          0.2  Iris-setosa
5      5.400000     3.048322           1.7          0.4  Iris-setosa
6      4.600000     3.400000           1.4          0.3  Iris-setosa
7      5.000000     3.400000           1.5          0.2  Iris-setosa
8      4.400000     2.900000           1.4          0.2  Iris-setosa
9      4.900000     3.100000           1.5          0.1  Iris-setosa

In [17]:

df_preprocessed = df.copy()

print("✓ Preprocessing copy created successfully.")
print(f"Original dataset shape    : {df.shape}")
print(f"Preprocessing dataset shape: {df_preprocessed.shape}")

✓ Preprocessing copy created successfully.
Original dataset shape    : (150, 5)
Preprocessing dataset shape: (150, 5)

In [18]:

df_preprocessed.loc[0, "sepal_length"] = np.nan
df_preprocessed.loc[5, "sepal_width"] = np.nan
df_preprocessed.loc[10, "petal_width"] = np.nan

print("Missing values introduced for demonstration")
print("=" * 60)

display(df_preprocessed.isnull().sum().to_frame(name="Missing Count"))

Missing values introduced for demonstration
============================================================

              Missing Count
sepal_length              1
sepal_width               1
petal_length              0
petal_width               1
species                   0

In [19]:

numeric_columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width"
]

for column in numeric_columns:
    df_preprocessed[column] = df_preprocessed[column].fillna(
        df_preprocessed[column].mean()
    )

print("✓ Missing values handled using Mean Imputation")
print("=" * 60)

display(df_preprocessed.isnull().sum().to_frame(name="Missing Count"))

✓ Missing values handled using Mean Imputation
============================================================

              Missing Count
sepal_length              0
sepal_width               0
petal_length              0
petal_width               0
species                   0

In [20]:
print("Categorical Column")
print("=" * 60)

print("Column:", "species")
print("\nUnique categories:")

for category in df_preprocessed["species"].unique():
    print("•", category)

Categorical Column
============================================================
Column: species

Unique categories:
• Iris-setosa
• Iris-versicolor
• Iris-virginica

In [21]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()

df_preprocessed[numeric_columns] = scaler.fit_transform(
    df_preprocessed[numeric_columns]
)

print("✓ Numerical features normalized using Min-Max Scaling")
print("=" * 60)

✓ Numerical features normalized using Min-Max Scaling
============================================================

In [22]:
print("Dataset After Normalization")
print("=" * 80)

display(df_preprocessed.head(10))

Dataset After Normalization
================================================================================

   sepal_length  sepal_width  petal_length  petal_width      species
0      0.430089     0.625000      0.067797     0.041667  Iris-setosa
1      0.166667     0.416667      0.067797     0.041667  Iris-setosa
2      0.111111     0.500000      0.050847     0.041667  Iris-setosa
3      0.083333     0.458333      0.084746     0.041667  Iris-setosa
4      0.194444     0.666667      0.067797     0.041667  Iris-setosa
5      0.305556     0.436801      0.118644     0.125000  Iris-setosa
6      0.083333     0.583333      0.067797     0.083333  Iris-setosa
7      0.194444     0.583333      0.084746     0.041667  Iris-setosa
8      0.027778     0.375000      0.067797     0.041667  Iris-setosa
9      0.166667     0.458333      0.084746     0.000000  Iris-setosa

In [23]:
print("Minimum Values After Normalization")
print("=" * 60)

display(df_preprocessed[numeric_columns].min().to_frame(name="Minimum"))

print("\nMaximum Values After Normalization")
print("=" * 60)

display(df_preprocessed[numeric_columns].max().to_frame(name="Maximum"))

Minimum Values After Normalization
============================================================

              Minimum
sepal_length      0.0
sepal_width       0.0
petal_length      0.0
petal_width       0.0

Maximum Values After Normalization
============================================================

              Maximum
sepal_length      1.0
sepal_width       1.0
petal_length      1.0
petal_width       1.0

In [24]:
comparison = pd.DataFrame({
    "Feature": numeric_columns,
    "Original Mean": [
        df[column].mean() for column in numeric_columns
    ],
    "Normalized Mean": [
        df_preprocessed[column].mean() for column in numeric_columns
    ]
})

display(comparison)

        Feature  Original Mean  Normalized Mean
0  sepal_length       5.843333         0.430089
1   sepal_width       3.054000         0.436801
2  petal_length       3.758667         0.467571
3   petal_width       1.198667         0.460570

In [25]:
print("FINAL PREPROCESSED DATASET")
print("=" * 80)

print("Rows    :", df_preprocessed.shape[0])
print("Columns :", df_preprocessed.shape[1])

print("\nMissing values:")
print(df_preprocessed.isnull().sum().sum())

print("\n✓ Missing values handled")
print("✓ Categorical data encoded")
print("✓ Numerical data normalized")

FINAL PREPROCESSED DATASET
================================================================================
Rows    : 150
Columns : 5

Missing values:
0

✓ Missing values handled
✓ Categorical data encoded
✓ Numerical data normalized

In [26]:
print("Final Preprocessed Dataset")
print("=" * 80)

display(df_preprocessed.head(15))

Final Preprocessed Dataset
================================================================================

    sepal_length  sepal_width  petal_length  petal_width      species
0       0.430089     0.625000      0.067797     0.041667  Iris-setosa
1       0.166667     0.416667      0.067797     0.041667  Iris-setosa
2       0.111111     0.500000      0.050847     0.041667  Iris-setosa
3       0.083333     0.458333      0.084746     0.041667  Iris-setosa
4       0.194444     0.666667      0.067797     0.041667  Iris-setosa
5       0.305556     0.436801      0.118644     0.125000  Iris-setosa
6       0.083333     0.583333      0.067797     0.083333  Iris-setosa
7       0.194444     0.583333      0.084746     0.041667  Iris-setosa
8       0.027778     0.375000      0.067797     0.041667  Iris-setosa
9       0.166667     0.458333      0.084746     0.000000  Iris-setosa
10      0.305556     0.708333      0.084746     0.460570  Iris-setosa
11      0.138889     0.583333      0.101695     0.041667  Iris-setosa
12      0.138889     0.416667      0.067797     0.000000  Iris-setosa
13      0.000000     0.416667      0.016949     0.000000  Iris-setosa
14      0.416667     0.833333      0.033898     0.041667  Iris-setosa